### ISSUE TITLE
Ignore UI

### ISSUE THREAD

**Issue by Geneworm** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#2]
I have two cameras in my scene, one to render the UI and one to render everything else. I understand that this is probably using android intents so may not be possible but is there a way I can use this to record from only one camera rather than everything on screen?

**Comment by thanh-nguyen-kim** [comment]
I recommend you to buy this plugin.
https://forum.unity.com/threads/natcorder-video-recording-api.505146/
In order to record from one camera, we need to use Graphics.Blit() to get the image matrix and use an additional plugin (FFMPEG) to combine them to a video. This is a very complicate process and may cost you several months of coding, so buy a plugin is a better choice for you

**Comment by Geneworm** [comment]
Ok thanks for the advice I'll have a look at it
